### PR TITLE
v1.11.0

### PR DESCRIPTION
**Pull request by m-schmoock**
- update to 1.11.0
- fixes a alpine package repository issue that prevented building

### CODE REVIEW

**Comment by lukechilds** [comment]
@m-schmoock thanks!

The Alping package issue, is that just relevant for this version, or will it affect building all historical versions too?

e.g If I checkout `v1.10.0` in this repo will it fail to build unless I change the alpine repo link too?

**Comment by m-schmoock** [comment]
@lukechilds I think it affects building other (older) versions as well, as alpine seemed to move the leveldb stuff to the other repo.

**Comment by lukechilds** [comment]
Ah ok.

Would you mind submitting this ass two separate commits/PRs?

I like to squash PRs into a single commit in master and keep one atomic change per commit.

It will also mean I can cherry pick the alpine repo commit into all other version branches so people can still build old ElectrumX version images if they want to.

**Comment by m-schmoock** [comment]
will do

**Pull request closed without merging**
