### PR TITLE
 bumped version and changed env for v1.12.0 

### PR DESCRIPTION
**Pull request by Mave95**

### CODE REVIEW

**Comment by Mave95** [comment]
Travis fails because the release of electrumx is tagged 1.12.0 while the version in the python file is 1.12

**Comment by lukechilds** [comment]
Thanks for this!

Are you able to split this into two separate PRs?

One for updating to 1.12, and a separate PR exposing WebSocket and RPC ports.

Also, have you tested RPC works from the host when you bind it to 127.0.0.1? I haven't tested but it probably won't accept requests coming from the Docker host. Would probably be best to accept all connections and let the user decide whether they expose the port via Docker or not and which interface to bind it to.

**Comment by Mave95** [comment]
I haven't split this in two PR because one wouldn't work without the other. Binding RPC that way enables the electrumx_rpc command to be executed inside the container for things like getinfo or peers.

**Comment by lukechilds** [comment]
But RPC isn't required to use ElectrumX. So I would class that as a new feature, unrelated to supporting v1.12.0.

Or am I misunderstanding something?

>Binding RPC that way enables the electrumx_rpc command to be executed inside the container for things like getinfo or peers.

Yeah I get that, I just mean I don't think this way will work from the host. I think it would be better if we bound RPC to `rpc://:8000` so it allows non-loopback connections. That way it can be exposed through Docker which is still safe because people can bind the Docker port to loopback only.

**Pull request closed without merging**
