### PR TITLE
Updated to spesmilo's fork

### PR DESCRIPTION
**Pull request by bavarianledger**
The original author dropped support for Bitcoin, which we intend to keep.

### CODE REVIEW

**Comment by lukechilds** [comment]
Thanks!

Sorry for the delay, I'm really busy atm.

Definitely want to merge this but just need to find some time to test it on my setup and document any changes.

**Comment by maltokyo** [comment]
Hi @lukechilds would you need some help to test etc?  Would be really nice to switch away from the https://github.com/kyuupichan/electrumx version ASAP, for peace of mind..

**Comment by schildbach** [comment]
I wonder does the current docker image still work without this patch? Because my electrumx has stopped updating blocks about 2 weeks ago and I don't have an idea why?

**Comment by Mave95** [comment]
I don't see a reason why it shouldn't work without the patch. My container is running fine and is fully synced. Since there hasn't been any new release from the fork it won't make a difference, unless the Dockerfile is modified to use the master branch instead of a specific version. Regarding your problem: My first guess would be to check if there's enough free disk space available.

**Comment by maltokyo** [comment]
@lukechilds would you mind to merge this when you have time.  Thank you!

**Comment by lukechilds** [comment]
Merged and pushed a new release based on the latest Spesmilo release.

**Pull request merged**
